services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: export_pos_db
    volumes:
      - mysql_data:/var/lib/mysql

  jsp-pos:
    image: jack299/myjsp1
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/pp
    environment:
      - CATALINA_OPTS=-Xmx512m
    depends_on:
      - db

volumes:
  mysql_data:
